// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrldlDDdm4ZB4MDlUgwIH80cSe7fBAvPg',
    appId: '1:49744994069:android:7a71349f38db5ca418131c',
    messagingSenderId: '49744994069',
    projectId: 'flutter-project-79b9e',
    databaseURL: 'https://flutter-project-79b9e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-79b9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC4ZZqpz1q6RurPaNG129y2F0JVszHJao',
    appId: '1:49744994069:ios:118fbacc914844b318131c',
    messagingSenderId: '49744994069',
    projectId: 'flutter-project-79b9e',
    databaseURL: 'https://flutter-project-79b9e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-79b9e.appspot.com',
    iosClientId: '49744994069-1oqq1e0giq4lbe7bi8fs4on6esu3r4v2.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitirme',
  );
}
